export const CATEGORY_KEYWORDS: [string, string[]][] = [
    ['Food', [
        'comi', 'almo', 'jant', 'pequen', 'refeic', 'lanche', 'petisco', 'snack',
        'restaur', 'cafe', 'cafet', 'pastel', 'padari', 'mercear', 'talho', 'peixar',
        'minimercado', 'minipreco', 'continente', 'pingo doce', 'intermarche', 'lidl', 'aldi', 'jumbo', 'netto',
        'glovo', 'uber eat', 'ubereats', 'deliveroo', 'ifood', 'just eat', 'bolt food',
        'aliment', 'mercearia', 'frutas', 'legumes', 'vegetais',
        'cerveja', 'vinho', 'refrigerante', 'sumo', 'gelado', 'sorvete', 'bolo', 'doce',
        'grocery', 'supermarket', 'bakery', 'deli', 'diner', 'bistro', 'canteen', 'buffet', 'takeaway',
        'food', 'lunch', 'dinner', 'breakfast', 'meal', 'drink', 'coffee', 'tea',
        'doordash', 'grubhub', 'postmates',
        'pizza', 'sushi', 'hambur', 'kebab', 'sandwich', 'wrap', 'taco', 'burrito', 'salad', 'ramen', 'noodle',
        'burger king', 'burgerking', 'mcdonald', 'kfc', 'subway', 'domino', 'pizza hut',
        'nandos', 'five guys', 'starbucks', 'dunkin', 'costa coffee', 'tim horton', 'greggs',
        'taco bell', 'wendy', 'popeyes', 'chipotle',
    ]],
    ['Transportation', [
        'uber', 'bolt', 'taxi', 'taxe', 'cabify', 'lyft', 'blablacar', 'carpooling',
        'metro', 'autocarro', 'comboio', 'cp ', 'renfe', 'andante', 'navegante', 'viva viagem', 'passe',
        'eletrico', 'tram', 'ferry', 'barco',
        'gasolina', 'combustiv', 'diesel', 'portagem', 'estacion', 'parking', 'vinheta',
        'revisao', 'inspecao', 'pneu', 'oleo', 'oficina', 'mecanico',
        'fuel', 'petrol', 'toll', 'car wash', 'rent a car', 'hertz', 'avis', 'europcar', 'sixt',
        'bicicleta', 'trotinete', 'gira', 'lime', 'bird',
        'flight', 'voo', 'aviao', 'ryanair', 'tap ', 'easyjet', 'wizzair', 'wizz air',
        'transavia', 'vueling', 'iberia', 'lufthansa', 'klm', 'british airways',
        'transport', 'bus', 'train', 'transit',
    ]],
    ['Entertainment', [
        'netflix', 'hbo', 'disney', 'apple tv', 'prime video', 'paramount', 'peacock',
        'crunchyroll', 'mubi', 'discovery', 'dazn', 'sport tv',
        'spotify', 'apple music', 'deezer', 'tidal', 'youtube music', 'soundcloud',
        'steam', 'playstation', 'xbox', 'nintendo', 'games', 'ubisoft',
        'twitch', 'game pass', 'psn', 'ps plus',
        'cinema', 'concerto', 'teatro', 'espetaculo', 'museu', 'parque', 'festival',
        'bilhete', 'ingresso', 'ticket', 'eventbrite', 'feira', 'expo',
        'futebol', 'basket', 'basquet', 'basquete', 'volei', 'rugby', 'golfe', 'golf',
        'natacao', 'swim', 'corrida', 'run', 'ciclismo',
        'livro', 'book', 'kindle', 'audible', 'revista', 'magazine', 'jornal',
        'puzzle', 'board game', 'hobby', 'craft',
        'casino', 'aposta', 'bet', 'lotaria', 'raspadinha',
        'youtube', 'jogo', 'game', 'concert', 'show', 'entret', 'filme', 'movie', 'music',
    ]],
    ['Utilities', [
        'eletric', 'energia', 'edp', 'endesa', 'iberdrola', 'enel', 'luz',
        'epal', 'aguas de ', 'servico aguas',
        'internet', 'fibra', 'wifi', 'nos ', 'meo ', 'vodafone', 'nowo', 'altice', 'digi',
        'nos fibra', 'meo total', 'tv cabo',
        'telef', 'telemo', 'phone', 'mobile', 'lycamobile',
        'gas', 'galp', 'goldenergy', 'repsol energia',
        'seguro casa', 'seguro multirisco', 'condominio',
        'utility', 'electric', 'water bill',
    ]],
    ['Health', [
        'farmaci', 'parafarmaci', 'farmacontinente', 'wells ', 'clinica', 'hospital', 'urgencia',
        'laboratorio', 'unilabs', 'synlab',
        'consulta', 'dentist', 'oculist', 'oftalmo', 'ortoped', 'cirurgi',
        'fisio', 'psicolog', 'nutri', 'analise', 'exame', 'radiologi', 'ecografi',
        'medic', 'vitamina', 'suplemento', 'protei', 'whey',
        'ginasi', 'gym', 'fitness', 'crossfit', 'pilates', 'yoga', 'spa', 'massagem', 'acupuntura', 'osteopat',
        'oculos', 'lente de contato',
        'seguro saude', 'seguro de saude', 'health insurance',
        'health', 'saude', 'pharmacy', 'doctor', 'therapy', 'supplement', 'wellness',
    ]],
    ['Housing', [
        'renda', 'aluguel', 'condomi', 'hipoteca', 'escritura',
        'obras', 'reparac', 'canalizador', 'eletricista', 'serralheiro', 'carpinteiro',
        'pedreiro', 'pintor', 'telhado', 'janela',
        'ikea', 'leroy merlin', 'aki ', 'brico depot', 'bricolag',
        'mobilia', 'movel', 'frigorifico', 'maquina lavar', 'microondas', 'eletrodomest',
        'jardim', 'garden', 'planta', 'detergent', 'limpeza',
        'rent', 'housing', 'mortgage', 'condomin', 'imobili', 'furniture', 'appliance',
    ]],
    ['Clothes', [
        'roupa', 'vestuario', 'calcado', 'sapato', 'bota', 'sandalia',
        'casaco', 'camisola', 'camisa', 'calca', 'saia', 'blusa', 'polo',
        'hoodie', 'sweatshirt', 'sweater', 'fato', 'gravata', 'cinto',
        'meia', 'cueca', 'lingerie', 'bikini', 'fato de banho',
        'chapeu', 'bone', 'luva', 'cachecol', 'mala', 'carteira', 'bolsa',
        'colar', 'pulseira', 'anel', 'brinco', 'oculos de sol', 'relogio',
        'zara', 'primark', 'mango', 'pull and bear', 'bershka', 'stradivari', 'massimo dutti',
        'springfield', 'salsa', 'sport zone', 'footlocker', 'jd sport', 'parfois', 'seaside',
        'h&m', 'uniqlo', 'gap', 'forever 21', 'asos', 'shein', 'zalando',
        'nike', 'adidas', 'puma', 'new balance', 'reebok', 'under armour', 'fila',
        'converse', 'vans', 'timberland', 'north face', 'columbia', 'champion', 'carhartt',
        'decathlon',
        'levi', 'tommy hilfiger', 'lacoste', 'ralph lauren', 'calvin klein', 'diesel',
        'cloth', 'shirt', 'trouser', 'jacket', 'dress', 'jeans', 'sneaker',
        'boot', 'sock', 'underwear', 'swimwear', 'hat', 'scarf', 'glove',
        'bag', 'wallet', 'sunglasses', 'watch', 'fashion', 'apparel',
    ]],
];

export const QUERY_CATEGORY_KEYWORDS: [string, string[]][] = [
    ['Food',           ['comida', 'alimentacao', 'restaurante', 'supermercado', 'refeicao', 'food', 'mercado', 'groceries', 'grocery', 'supermarket', 'dining', 'eating']],
    ['Transportation', ['transporte', 'gasolina', 'combustivel', 'viagem', 'uber', 'transport', 'taxi', 'travel', 'commute', 'flight', 'car', 'fuel']],
    ['Entertainment',  ['entretenimento', 'lazer', 'cinema', 'jogos', 'musica', 'entertainment', 'leisure', 'gaming', 'streaming', 'movies', 'movie', 'hobby']],
    ['Utilities',      ['eletricidade', 'internet', 'gas natural', 'fatura', 'utilities', 'servicos', 'bills', 'bill', 'electricity', 'water bill', 'phone bill']],
    ['Health',         ['saude', 'farmacia', 'medico', 'clinica', 'hospital', 'health', 'medical', 'healthcare', 'pharmacy', 'doctor', 'medicine']],
    ['Housing',        ['habitacao', 'renda', 'aluguel', 'housing', 'casa', 'rent', 'mortgage', 'home']],
    ['Clothes',        ['roupa', 'vestuario', 'calcado', 'clothes', 'clothing', 'fashion', 'apparel', 'shopping']],
];

// Atenção: as palavras-chave batem como substring, por isso tokens de 3 letras
// como 'mes' ou 'ano' são perigosos (apanham "mesa", "itali-ano"...). Usamos
// palavras sem ambiguidade e as frases que as pessoas escrevem mesmo.
export const TYPE_KEYWORDS: [string, string[]][] = [
    ['Monthly',      ['mensal', 'monthly', 'subscri', 'subscription', 'recorrent', 'recurring', 'por mes', 'ao mes', '/mes']],
    ['Yearly',       ['anual', 'annual', 'yearly', 'por ano', 'ao ano', '/ano']],
];
